### ISSUE TITLE
Player disconnected with NullPointerException

### ISSUE THREAD

**Issue by ams2990** [BuiltBrokenModding/AddictedToRed#1]
I don't know what the player was doing to cause this. I'm using Cauldron build 1343 and AddictedtoRed 0.0.1b20.

```
[20:31:07 WARN]: Failed to handle packet for /91.119.211.97:53638
java.lang.NullPointerException
        at com.builtbroken.addictedtored.content.detector.selection.TileSelectionDetector.func_145841_b(TileSelectionDetector.java:147) ~[TileSelectionDetector.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.<init>(CraftBlockState.java:49) ~[CraftBlockState.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.getBlockState(CraftBlockState.java:87) ~[CraftBlockState.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraftforge.event.world.BlockEvent$PlaceEvent.<init>(BlockEvent.java:150) ~[BlockEvent$PlaceEvent.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent.<init>(BlockEvent.java:178) ~[BlockEvent$MultiPlaceEvent.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerMultiBlockPlace(ForgeEventFactory.java:59) ~[ForgeEventFactory.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:591) ~[ForgeHooks.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:147) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[20:31:07 INFO]: Hidri lost connection: Internal server error
[20:31:07 INFO]: Hidri left the game.
```

**Comment by dmodoomsirius** [comment]
Does this happen on a forge server?

Edit Was told this happens on forge server as well.

**Comment by ams2990** [comment]
I'm not positive, but I don't think so.

**Comment by ams2990** [comment]
Okay, just got confirmation. It doesn't happen on a Forge-only server, and is caused by placing an Area Detector.

**Comment by DarkGuardsman** [comment]
While I look into this how did you get a copy of Addicted to Red? As it has only been released inside the beta Voltz modpack

**Comment by DarkGuardsman** [comment]
Fixed 4886624c1aca50c3f071d56ca9e9cd34408b5358

**Comment by ams2990** [comment]
I'm the one running the server.

**Comment by ams2990** [comment]
Also, thanks for the quick fix.
